import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Banner from "../components/Banner";

const Home: NextPage = () => {
  return (
    <div className="relative h-[140vh]">
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main>
        <section></section>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
